### ISSUE TITLE
Override Services

### ISSUE THREAD

**Issue by agentschmitt** [SamhammerAG/Samhammer.DependencyInjection#12]
For projects that are build for multiple customers we may need different implementation types per customer.
It would be a good feature to allow override of an default implementation depending on which customer is configured in the project.

This is how we could set the override for an specific customer. 
We should only register overrides to service collection with matchting name.
```
services.ResolveDependencies(o => o.SetOverride("customer1"));
```

This is how we could mark an class as override to register into service collection.
We would need to register this service after the service at last to ensure our override instance will be used.
We would use still the registrationtypes from the baseclass in this case.
```
[Override("customer1"]
public class ClassCustomerA:  Class{}

[Inject(Target.Matching)]
public class Class : IClass {}
public interface IClass : IBaseClass {}
```

Alternative approach would be extending existing attributes with the override name.
```
[Inject(Target.Matching, override="customer1")]
public class ClassCustomerA:  Class{}

[Inject(Target.Matching)]
public class Class : IClass {}
public interface IClass : IBaseClass {}
```

Another approach would be adding new attributes with the override name.
```
[InjectOverride(Target.Matching, override="customer1")]
public class ClassCustomerA:  Class{}

[Inject(Target.Matching)]
public class Class : IClass {}
public interface IClass : IBaseClass {}
```

**Comment by devRoemer** [comment]
After some discussion, we decided to use the first approach. It is less prone to errors because it is not required to specify parameters like targets again (possibly with a different value...).
